language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install: composer install --dev

before_script: composer require satooshi/php-coveralls --prefer-dist

script: phpunit

after_script: php vendor/bin/coveralls -v