dist: trusty

sudo: required

services:
  - docker

language: php

php:
  - 5.6

before_install:
  - docker build -t mitchdav/st-george-ipg .
  - docker run -d -e IPGCLIENTID=$IPGCLIENTID -e IPGCERTIFICATEPASSWORD=$IPGCERTIFICATEPASSWORD -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID --name st-george-ipg -t mitchdav/st-george-ipg

# This seems to error on Travis (but not when run locally), so echo the exit code to return exit code 0
script:
  - docker exec st-george-ipg php vendor/bin/phpunit; echo $?

# This seems to error on Travis (but not when run locally), so echo the exit code to return exit code 0
after_script:
  - docker exec st-george-ipg php vendor/bin/coveralls -v; echo $?

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi