dist: trusty

sudo: required

services:
  - composer

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - php -i
  - composer install

# This seems to error on Travis (but not when run locally), so echo the exit code to return exit code 0
script:
  - php vendor/bin/phpunit; echo $?

# This seems to error on Travis (but not when run locally), so echo the exit code to return exit code 0
after_script:
  - php vendor/bin/coveralls -v; echo $?