dist: trusty

sudo: required

services:
  - composer

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -y
  - php -i
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then sudo apt-get install php5.6-curl; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo apt-get install php-curl; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then sudo apt-get install php-curl; fi
  - php -i
  - composer install

script:
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v