dist: trusty

sudo: required

services:
  - composer

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - php -i
  - sudo apt-get install php${TRAVIS_PHP_VERSION}-curl
  - php -i
  - composer install

script:
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v